/**
 * Generated by tsnapi — public API snapshot of `diff-build-output`
 */
// #region Types
export type CheckForDuplicateSymbolsOptions = Simplify<{
  readonly tsExtensions?: readonly LiteralUnion<`.d.${'c' | '' | 'm'}ts` | 'uncheckedindexed.ts', `${string}.${'c' | '' | 'm'}ts`>[];
  readonly jsExtensions?: readonly LiteralUnion<`.${'c' | '' | 'm'}js` | `${'index' | '.legacy-esm'}.js` | `.${'browser' | 'modern'}.mjs` | `.${'development' | 'production.min'}.cjs`, `${string}.${'c' | '' | 'm'}js`>[];
  readonly newFileContent: string;
  readonly verbose?: boolean;
} & DistributedOmit<ContentsInfo, 'relativePath' | 'relativePosixPath'>>;
export type CheckForPureAnnotationsOptions = Simplify<{
  readonly jsExtensions?: readonly LiteralUnion<`.${'c' | '' | 'm'}js` | `${'index' | '.legacy-esm'}.js` | `.${'browser' | 'modern'}.mjs` | `.${'development' | 'production.min'}.cjs`, `${string}.${'c' | '' | 'm'}js`>[];
  readonly newFileContent: string;
  readonly verbose?: boolean;
} & DistributedOmit<ContentsInfo, 'relativePath' | 'relativePosixPath'>>;
export type GenerateDiffReportsOptions = {
  checkForDuplicateSymbolsOptions?: WithEnabled<DistributedOmit<CheckForDuplicateSymbolsOptions, 'newFileContent' | 'newOutput' | 'oldOutput'>>;
  checkForPureAnnotationsOptions?: WithEnabled<DistributedOmit<CheckForPureAnnotationsOptions, 'newFileContent' | 'newOutput' | 'oldOutput'>>;
  viewVSCodeDiffOptions?: WithEnabled<DistributedOmit<ViewVSCodeDiffOptions, 'newOutput' | 'oldOutput'>>;
};
export type ViewVSCodeDiffOptions = Simplify<{
  includedExtensions?: readonly LiteralUnion<`.${'c' | '' | 'm'}js` | `${'index' | '.legacy-esm'}.js` | `.${'browser' | 'modern'}.mjs` | `.${'development' | 'production.min'}.cjs` | `.d.${'c' | '' | 'm'}ts` | 'uncheckedindexed.ts', string>[];
  excludedExtensions?: readonly string[];
  locale?: string;
  disableGpu?: boolean;
  disableLcdText?: boolean;
} & DistributedOmit<ContentsInfo, 'relativePath' | 'relativePosixPath'>>;
// #endregion

// #region Functions
export declare function generateDiffReports(generateDiffReportsOptions?: GenerateDiffReportsOptions): Promise<void>;
// #endregion

// #region Variables
export declare const checkForDuplicateSymbols: (checkForDuplicateSymbolsOptions: CheckForDuplicateSymbolsOptions, index: number) => void;
export declare const checkForPureAnnotations: (checkForPureAnnotationsOptions: CheckForPureAnnotationsOptions, index: number) => void;
export declare const viewVSCodeDiff: (viewVSCodeDiffOptions: ViewVSCodeDiffOptions) => Promise<ChildProcess | undefined>;
// #endregion